<?php
//; $Id: vrm_custom_comment.module,2012/08/01 10:18:33 Added for NIC $

function vrm_custom_comment_form_alter(&$form, $form_state, $form_id)
{
    drupal_add_js(drupal_get_path('module', 'vrm_custom_comment') . '/vrm_custom_comment.js');
    switch ($form_id) {
        case 'comment_form':
            $max_len = 3000;
            $node_id = $form['nid']['#value'];
            $node_obj = node_load($node_id);
            if (($node_obj->type == 'dataset') && (!user_access('administer'))) {
                $form['comment_filter']['comment'] = array(
                    '#type' => 'textarea',
                    '#title' => t('Comment'),
                    '#rows' => 15,
                    '#required' => TRUE,
                    '#description' => '<span id="discuss-textarea-limit-count"> ' . $max_len . ' </span> characters left.',
                    '#attributes' => array('onkeydown' => 'return textCounters(3000,"edit-comment")', 'onkeyup' => 'return textCounters(3000,"edit-comment")', 'id' => 'edit-comment', 'maxlength' => '3000')
                );
            }
            if ($node_obj->type == "feedback") {
                $path = 'node/' . $node_id . '/type/note';
                $form['#redirect'] = $path;

                $form['subject'] = array('#title' => '', '#default_value' => '');
                $form['name'] = array('#title' => '', '#default_value' => '', '#required' => FALSE);
                $form['comment_filter']['comment'] = array(
                    '#type' => 'textarea',
                    '#title' => t('Add Note:'),
                    '#rows' => 15,
                    '#description' => '<span id="note-textarea-limit-count"> ' . $max_len . ' </span> characters left.',
                    '#required' => TRUE,
                    '#attributes' => array('onkeydown' => 'textNoteCounters(3000,"edit-comment")', 'onkeyup' => 'textNoteCounters(3000,"edit-comment")', 'id' => 'edit-comment')
                );

                $form['_author'] = array('#title' => '', '#value' => '');
                $form['reset'] = array(
                    '#value' => '<input type="reset" value="Clear" class="form-submit" onclick="resetTextNoteCounters(3000);"> ', '#weight' => 100,
                );
				$path = drupal_get_path_alias($_GET['q']);
				$path = explode('/', $path);
				require_once(drupal_get_path('module','vrm_customization').'/vrm_customization.module');
				$page=$path[count($path)-1];
				if($page=='note')
				{
					drupal_set_title('Notes');
					vrm_customization_create_breadcrumb('notes');
				}
				else
				{
					vrm_customization_create_breadcrumb('view');
				}
			}

            break;
    }

}
