<?php
// $Id: decounter.module,v 1.3.2.5 2009/05/09 14:08:08 ivanjaros Exp $

// Generates content of the module's admin page.
function decounter_settings() {
  
  $q = db_query('SELECT rid, name FROM {role}');
  
  while ($fetch = db_fetch_object($q)) {
    $role[$fetch->rid] = $fetch->name;
  }
  
  $form['decounter_roles'] = array(
  '#type' => 'checkboxes',
  '#title' => t('Select roles'),
  '#description' => t('Select user roles to exclude from node views counting.'),
  '#default_value' => variable_get('decounter_roles', array()),
  '#options' => $role,
  '#multiple' => TRUE,
  '#weight' => -10,
  );
  
  $form['decounter']['decounter_exclude_admin'] = array(
  '#type' => 'checkbox',
  '#title' => t('Exclude admin'),
  '#description' => t('Check to exclude admin from node views counting.'),
  '#default_value' => variable_get('decounter_exclude_admin', '1'),
  '#multiple' => TRUE,
  '#weight' => 10,
  );

  return system_settings_form($form);  
}

  
/*
* Implementation of hook_menu().
* http://api.drupal.org/api/function/hook_menu/6
*/
function decounter_menu() {
  $items = array();
  
  $items['admin/settings/decounter'] = array(
    'title' => 'Decounter',
    'description' => 'Administer Decounter module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('decounter_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/*
* Implementation of hook_exit().
* http://api.drupal.org/api/function/hook_exit/6
*/
function decounter_exit() {
  global $user;
  
  $active = variable_get('statistics_count_content_views', 0);
  $exclude_roles = variable_get('decounter_roles', array());
  $exclude_admin = variable_get('decounter_exclude_admin', 1);

  foreach ($exclude_roles as $index => $value) {
    if (array_key_exists($value, $user->roles)) {
      $active_role = TRUE;
    }
  }
  
  if (($user->uid == '1') && ($exclude_admin == '1')) {
    $admin_out = TRUE;
  }

  if ($active && (arg(0) == 'node') && (is_numeric(arg(1))) && (arg(2) == '') && ($admin_out OR $active_role)) {
  db_query('UPDATE {node_counter} SET daycount = daycount - 1, totalcount = totalcount - 1 WHERE nid = %d', arg(1));
  }
}

?>