; This file was auto-generated by drush make
core = 6.x

api = 2
projects[drupal][version] = "6.x"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ogpl_communities][download][type] = ""
projects[ogpl_communities][download][url] = ""
projects[ogpl_communities][type] = "profile"

; Modules
projects[views_bulk_operations][version] = "1.13"

projects[ctools][version] = "1.8"

projects[comment_og][version] = "1.0"

projects[conditional_styles][version] = "1.2"

projects[features][version] = "1.2"

projects[og][version] = "2.2"

projects[og_features][version] = "1.3"

projects[og_forum][version] = "2.2"

projects[og_invite_link][version] = "1.0"

projects[og_user_roles][version] = "4.1"

projects[pathauto][version] = "1.6"

projects[revisioning][version] = "3.15"

projects[skinr][version] = "1.6"

projects[token][version] = "1.18"

projects[views][version] = "2.16"

projects[views_customfield][version] = "1.0"

; Themes
projects[fusion][version] = "1.12"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[datagov][download][type] = ""
projects[datagov][download][url] = ""
projects[datagov][type] = "theme"

