$Title="What is FAQ?"
$Question_Details="Privacy"
$Menu_Title="Enter Menu Title"
$Answer="OGPL guarantees the security of the reader.
Read more at: http://www.ndtv.com/article/cities/children-waiting-in-line-with-nursery-forms-faint-in-patna-reports-170891?pfrom=home-topstories&cp"
$Edit_log="Error"
$Audio_file=/D:\downloads\Beethoven's Symphony No. 9 (Scherzo).mp3/
$Video_file=/D:\downloads\traian.mpg/
$Days="2"
$exp_date="3 Feb 2013"
$invalid_date="1 Jan 2012"
$Content_Title="What is OGPL?"
$Comment="Edited by Content Creator"
$Mod_Title="What is OGPL by Moderator?"
$Mod_Comment="Edited by Moderator"