<?php
// $Id$

/**
 * @file
 * Filter status messages set by drupal_set_message().
 */

/**
 * Implements hook_boot().
 */
function jammer_messages_boot() {
  if (!empty($_SESSION['messages'])) {
    $results = db_query("SELECT message_string FROM {jammer_messages}");
    while ($message_filter = db_fetch_object($results)) {
      $message_filter = $message_filter->message_string;
      foreach ($_SESSION['messages'] as $type => $messages) {
        $grep_results = preg_grep('/'. $message_filter .'/', $_SESSION['messages'][$type]);
        foreach ($grep_results as $key => $match) {
          unset($_SESSION['messages'][$type][$key]);
        }
        if (empty($_SESSION['messages'][$type])) {
          unset($_SESSION['messages'][$type]);
        }
      }
    }
  }
}

/**
 * Implements hook_menu().
 *
 * @return An array of menu items.
 */
function jammer_messages_menu() {
  $items = array();

  $items['admin/settings/jammer/jammer_messages'] = array(
    'title' => 'Message Jammer',
    'description' => 'Filter status messages.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_jammer_messages_settings'),
    'access arguments' => array('administer site configuration')
  );
  $items['admin/settings/jammer/jammer_messages/delete/%'] = array(
    'title' => 'Message jammer delete',
    'description' => 'Delete filter on status messages.',
    'page callback' => 'jammer_messages_settings_delete',
    'page arguments' => array(5),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function _jammer_messages_settings() {
  $form = array();
  $form['jammer_messages_string'] = array(
    '#type' => 'textfield',
    '#title' => t('Message to jam'),
    '#required' => TRUE,
    '#description' => t('The message format is processed in regular expression form. Enter either an exact string to suppress, ' .
    'or one which matches !PCRE formatting.', array('!PCRE' => l('PCRE', 'http://us3.php.net/manual/en/book.pcre.php', array('external' => TRUE)))),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Jam message',
  );
  $current_settings = db_query("SELECT mid, message_string FROM {jammer_messages}");
  $headers = array(t('Message Pattern ID'), t('Message Pattern'), t('Delete'));
  $data = array();
  while ($setting = db_fetch_object($current_settings)) {
    $data[] = array(
      $setting->mid,
      $setting->message_string,
      l(t('Delete'), 'admin/settings/jammer/jammer_messages/delete/' . $setting->mid),
    );
  }
  if (!empty($data)) {
    $form['configured'] = array(
      '#type' => 'fieldset',
      '#title' => 'Jammed messages',
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $form['configured']['table'] = array(
      '#type' => 'item',
      '#value' => theme('table', $headers, $data),
    );
  }
  return $form;
}

function _jammer_messages_settings_submit($orm, &$form_state) {
  $form_values = $form_state['values'];
  if ($form_values['jammer_messages_string'] == '') {
    drupal_set_message(t('Empty strings are not an accepted match string.'));
    return;
  }
  $message->message_string = $form_values['jammer_messages_string'];
  drupal_write_record('jammer_messages', $message);
}

function jammer_messages_settings_delete($mid) {
  db_query('DELETE FROM {jammer_messages} WHERE mid = %d', array($mid));
  drupal_set_message(t('Jammer filter #@mid has been deleted.', array('@mid'=>$mid)));
  drupal_goto('admin/settings/jammer/jammer_messages');
}
